version: '3.6'
services:
 sqlserver:
   image: "mcr.microsoft.com/mssql/server:2019-latest"
   environment: 
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "manso098_"
     MYSQL_PID: "Express"
   ports:
    - "1433:1433"

